name: upload-to-allure-testops

on:
  workflow_dispatch:
    inputs:
      TEST_ENDPOINT:
        description: "Endpoint for tests"
        required: true
        default: https://testing.qatools.cloud
      ALLURE_JOB_RUN_ID:
        description: "ALLURE_JOB_RUN_ID service parameter. Leave blank."
        required: false
      ALLURE_USERNAME:
        description: "ALLURE_USERNAME service parameter. Leave blank"
        required: false

env:
  ALLURE_RESULTS: "allure-results"
  ALLURE_ENDPOINT: https://testing.qatools.cloud/
  ALLURE_PROJECT_ID: 1605
  ALLURE_TOKEN: 67aad6fa-966a-49ef-a598-e572b3e030f9

jobs:
  gradle-tests:
    runs-on: ubuntu-latest  # или windows-latest, если предпочитаете Windows
    
steps:
  - uses: actions/checkout@v3
  
  - name: Set up JDK
    uses: actions/setup-java@v3
    with:
      distribution: 'temurin'
      java-version: '17'
  
  - name: Cache Gradle dependencies
    uses: actions/cache@v3
    with:
      path: ~/.gradle/caches
      key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/gradle.properties') }}
      restore-keys: |
        ${{ runner.os }}-gradle-
  
  - name: Install Chrome
    run: |
      sudo apt-get update
      sudo apt-get install -y chromium-browser
  
  - name: Build with Gradle
    run: gradle build
  
  # ... rest of workflow
      
      - name: Install Allure CLI
        uses: allure-framework/setup-allurectl@v1
        with:
          allure-endpoint: ${{ env.ALLURE_ENDPOINT }}
          allure-token: ${{ env.ALLURE_TOKEN }}
          allure-project-id: ${{ env.ALLURE_PROJECT_ID }}
      
      - name: Run Tests and Generate Reports
        run: |
          # Запускаем тесты, предполагается, что они настроены на сбор отчётов Allure в папке allure-results
          gradle test
          
          # Запускаем watcher для автоматической отправки результатов
          allurectl watch --project-id ${{ env.ALLURE_PROJECT_ID }} --results-path ${{ env.ALLURE_RESULTS }} --token ${{ env.ALLURE_TOKEN }}
        env:
          TEST_ENDPOINT: ${{ github.event.inputs.TEST_ENDPOINT }}
