name: upload-to-allure-testops

on:
  workflow_dispatch:
    inputs:
      TEST_ENDPOINT:
        description: "Endpoint for tests"
        required: true
        default: https://testing.qatools.cloud
      ALLURE_JOB_RUN_ID:
        description: "ALLURE_JOB_RUN_ID service parameter. Leave blank."
        required: false
      ALLURE_USERNAME:
        description: "ALLURE_USERNAME service parameter. Leave blank"
        required: false

env:
  ALLURE_RESULTS: "allure-results"
  ALLURE_ENDPOINT: https://testing.qatools.cloud/
  ALLURE_PROJECT_ID: 1605
  ALLURE_TOKEN: 67aad6fa-966a-49ef-a598-e572b3e030f9

jobs:
  selenide-tests:
    runs-on: ubuntu-latest  # или windows-latest, если нужна Windows среда
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # или другую версию по вашему проекту
      
      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      
      - name: Build Project
        run: mvn clean verify  # или gradle build, если используете Gradle
      
      - name: Install Allure CLI
        uses: allure-framework/setup-allurectl@v1
        with:
          allure-endpoint: ${{ env.ALLURE_ENDPOINT }}
          allure-token: ${{ env.ALLURE_TOKEN }}
          allure-project-id: ${{ env.ALLURE_PROJECT_ID }}
      
      - name: Run Selenide Tests and Generate Allure Reports
        run: |
          # Запускаем тесты. Предполагается, что ваши тесты настроены на генерацию отчётов в allure-results
          mvn test
          
          # После завершения тестов запускаем watcher для загрузки результатов
          allurectl watch --project-id ${{ env.ALLURE_PROJECT_ID }} --results-path ${{ env.ALLURE_RESULTS }} --token ${{ env.ALLURE_TOKEN }}
        env:
          TEST_ENDPOINT: ${{ github.event.inputs.TEST_ENDPOINT }}
          # при необходимости добавьте другие переменные окружения
